# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/keyur/Documents/Vivado/Processor/Processor.srcs/sources_1/bd/uproc_top_level/ip/uproc_top_level_blk_mem_gen_0_2/uproc_top_level_blk_mem_gen_0_2.xci
# IP: The module: 'uproc_top_level_blk_mem_gen_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/keyur/Documents/Vivado/Processor/Processor.gen/sources_1/bd/uproc_top_level/ip/uproc_top_level_blk_mem_gen_0_2/uproc_top_level_blk_mem_gen_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uproc_top_level_blk_mem_gen_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/keyur/Documents/Vivado/Processor/Processor.srcs/sources_1/bd/uproc_top_level/ip/uproc_top_level_blk_mem_gen_0_2/uproc_top_level_blk_mem_gen_0_2.xci
# IP: The module: 'uproc_top_level_blk_mem_gen_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/keyur/Documents/Vivado/Processor/Processor.gen/sources_1/bd/uproc_top_level/ip/uproc_top_level_blk_mem_gen_0_2/uproc_top_level_blk_mem_gen_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uproc_top_level_blk_mem_gen_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
