# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/keyur/Documents/Vivado/Processor/Processor.srcs/sources_1/bd/uproc_top_level/ip/uproc_top_level_rgb2dvi_0_0/uproc_top_level_rgb2dvi_0_0.xci
# IP: The module: 'uproc_top_level_rgb2dvi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/keyur/Documents/Vivado/Processor/Processor.gen/sources_1/bd/uproc_top_level/ip/uproc_top_level_rgb2dvi_0_0/src/rgb2dvi.xdc
# XDC: The top module name and the constraint reference have the same name: 'uproc_top_level_rgb2dvi_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/keyur/Documents/Vivado/Processor/Processor.gen/sources_1/bd/uproc_top_level/ip/uproc_top_level_rgb2dvi_0_0/src/rgb2dvi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uproc_top_level_rgb2dvi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/keyur/Documents/Vivado/Processor/Processor.gen/sources_1/bd/uproc_top_level/ip/uproc_top_level_rgb2dvi_0_0/src/rgb2dvi_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'uproc_top_level_rgb2dvi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/keyur/Documents/Vivado/Processor/Processor.srcs/sources_1/bd/uproc_top_level/ip/uproc_top_level_rgb2dvi_0_0/uproc_top_level_rgb2dvi_0_0.xci
# IP: The module: 'uproc_top_level_rgb2dvi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/keyur/Documents/Vivado/Processor/Processor.gen/sources_1/bd/uproc_top_level/ip/uproc_top_level_rgb2dvi_0_0/src/rgb2dvi.xdc
# XDC: The top module name and the constraint reference have the same name: 'uproc_top_level_rgb2dvi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/keyur/Documents/Vivado/Processor/Processor.gen/sources_1/bd/uproc_top_level/ip/uproc_top_level_rgb2dvi_0_0/src/rgb2dvi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uproc_top_level_rgb2dvi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/keyur/Documents/Vivado/Processor/Processor.gen/sources_1/bd/uproc_top_level/ip/uproc_top_level_rgb2dvi_0_0/src/rgb2dvi_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'uproc_top_level_rgb2dvi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
