# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ZyboZ7-10.xdc

# Block Designs: bd/uproc_top_level/uproc_top_level.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uproc_top_level || ORIG_REF_NAME==uproc_top_level} -quiet] -quiet

# IP: bd/uproc_top_level/ip/uproc_top_level_blk_mem_gen_0_1/uproc_top_level_blk_mem_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uproc_top_level_blk_mem_gen_0_1 || ORIG_REF_NAME==uproc_top_level_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/uproc_top_level/ip/uproc_top_level_blk_mem_gen_0_2/uproc_top_level_blk_mem_gen_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uproc_top_level_blk_mem_gen_0_2 || ORIG_REF_NAME==uproc_top_level_blk_mem_gen_0_2} -quiet] -quiet

# IP: bd/uproc_top_level/ip/uproc_top_level_clock_div_0_0/uproc_top_level_clock_div_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uproc_top_level_clock_div_0_0 || ORIG_REF_NAME==uproc_top_level_clock_div_0_0} -quiet] -quiet

# IP: bd/uproc_top_level/ip/uproc_top_level_clock_div_25_0_0/uproc_top_level_clock_div_25_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uproc_top_level_clock_div_25_0_0 || ORIG_REF_NAME==uproc_top_level_clock_div_25_0_0} -quiet] -quiet

# IP: bd/uproc_top_level/ip/uproc_top_level_debounce_0_0/uproc_top_level_debounce_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uproc_top_level_debounce_0_0 || ORIG_REF_NAME==uproc_top_level_debounce_0_0} -quiet] -quiet

# IP: bd/uproc_top_level/ip/uproc_top_level_uart_0_0/uproc_top_level_uart_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uproc_top_level_uart_0_0 || ORIG_REF_NAME==uproc_top_level_uart_0_0} -quiet] -quiet

# IP: bd/uproc_top_level/ip/uproc_top_level_rgb2dvi_0_0/uproc_top_level_rgb2dvi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uproc_top_level_rgb2dvi_0_0 || ORIG_REF_NAME==uproc_top_level_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/uproc_top_level/ip/uproc_top_level_xlconcat_0_0/uproc_top_level_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uproc_top_level_xlconcat_0_0 || ORIG_REF_NAME==uproc_top_level_xlconcat_0_0} -quiet] -quiet

# IP: bd/uproc_top_level/ip/uproc_top_level_xlconstant_0_0/uproc_top_level_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uproc_top_level_xlconstant_0_0 || ORIG_REF_NAME==uproc_top_level_xlconstant_0_0} -quiet] -quiet

# IP: bd/uproc_top_level/ip/uproc_top_level_xlconstant_1_0/uproc_top_level_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uproc_top_level_xlconstant_1_0 || ORIG_REF_NAME==uproc_top_level_xlconstant_1_0} -quiet] -quiet

# IP: bd/uproc_top_level/ip/uproc_top_level_regs_0_0/uproc_top_level_regs_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uproc_top_level_regs_0_0 || ORIG_REF_NAME==uproc_top_level_regs_0_0} -quiet] -quiet

# IP: bd/uproc_top_level/ip/uproc_top_level_my_alu_0_0/uproc_top_level_my_alu_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uproc_top_level_my_alu_0_0 || ORIG_REF_NAME==uproc_top_level_my_alu_0_0} -quiet] -quiet

# IP: bd/uproc_top_level/ip/uproc_top_level_controls_0_0/uproc_top_level_controls_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uproc_top_level_controls_0_0 || ORIG_REF_NAME==uproc_top_level_controls_0_0} -quiet] -quiet

# IP: bd/uproc_top_level/ip/uproc_top_level_framebuffer_0_0/uproc_top_level_framebuffer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uproc_top_level_framebuffer_0_0 || ORIG_REF_NAME==uproc_top_level_framebuffer_0_0} -quiet] -quiet

# IP: bd/uproc_top_level/ip/uproc_top_level_pixel_pusher_0_0/uproc_top_level_pixel_pusher_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uproc_top_level_pixel_pusher_0_0 || ORIG_REF_NAME==uproc_top_level_pixel_pusher_0_0} -quiet] -quiet

# IP: bd/uproc_top_level/ip/uproc_top_level_vga_ctrl_0_0/uproc_top_level_vga_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uproc_top_level_vga_ctrl_0_0 || ORIG_REF_NAME==uproc_top_level_vga_ctrl_0_0} -quiet] -quiet

# XDC: c:/Users/keyur/Documents/Vivado/Processor/Processor.gen/sources_1/bd/uproc_top_level/uproc_top_level_ooc.xdc
