# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/keyur/Documents/Vivado/HDMI_tester/HDMI_tester.srcs/sources_1/bd/HDMI_Tester/ip/HDMI_Tester_blk_mem_gen_0_0/HDMI_Tester_blk_mem_gen_0_0.xci
# IP: The module: 'HDMI_Tester_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/keyur/Documents/Vivado/HDMI_tester/HDMI_tester.gen/sources_1/bd/HDMI_Tester/ip/HDMI_Tester_blk_mem_gen_0_0/HDMI_Tester_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'HDMI_Tester_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/keyur/Documents/Vivado/HDMI_tester/HDMI_tester.srcs/sources_1/bd/HDMI_Tester/ip/HDMI_Tester_blk_mem_gen_0_0/HDMI_Tester_blk_mem_gen_0_0.xci
# IP: The module: 'HDMI_Tester_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/keyur/Documents/Vivado/HDMI_tester/HDMI_tester.gen/sources_1/bd/HDMI_Tester/ip/HDMI_Tester_blk_mem_gen_0_0/HDMI_Tester_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'HDMI_Tester_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
