# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Zybo-Z710.xdc

# Block Designs: bd/HDMI_Tester/HDMI_Tester.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HDMI_Tester || ORIG_REF_NAME==HDMI_Tester} -quiet] -quiet

# IP: bd/HDMI_Tester/ip/HDMI_Tester_clock_div_25_0_0/HDMI_Tester_clock_div_25_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HDMI_Tester_clock_div_25_0_0 || ORIG_REF_NAME==HDMI_Tester_clock_div_25_0_0} -quiet] -quiet

# IP: bd/HDMI_Tester/ip/HDMI_Tester_pixel_pusher_0_0/HDMI_Tester_pixel_pusher_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HDMI_Tester_pixel_pusher_0_0 || ORIG_REF_NAME==HDMI_Tester_pixel_pusher_0_0} -quiet] -quiet

# IP: bd/HDMI_Tester/ip/HDMI_Tester_vga_ctrl_0_0/HDMI_Tester_vga_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HDMI_Tester_vga_ctrl_0_0 || ORIG_REF_NAME==HDMI_Tester_vga_ctrl_0_0} -quiet] -quiet

# IP: bd/HDMI_Tester/ip/HDMI_Tester_xlconstant_0_0/HDMI_Tester_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HDMI_Tester_xlconstant_0_0 || ORIG_REF_NAME==HDMI_Tester_xlconstant_0_0} -quiet] -quiet

# IP: bd/HDMI_Tester/ip/HDMI_Tester_xlconcat_0_0/HDMI_Tester_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HDMI_Tester_xlconcat_0_0 || ORIG_REF_NAME==HDMI_Tester_xlconcat_0_0} -quiet] -quiet

# IP: bd/HDMI_Tester/ip/HDMI_Tester_blk_mem_gen_0_0/HDMI_Tester_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HDMI_Tester_blk_mem_gen_0_0 || ORIG_REF_NAME==HDMI_Tester_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/HDMI_Tester/ip/HDMI_Tester_xlconstant_1_0/HDMI_Tester_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HDMI_Tester_xlconstant_1_0 || ORIG_REF_NAME==HDMI_Tester_xlconstant_1_0} -quiet] -quiet

# IP: bd/HDMI_Tester/ip/HDMI_Tester_rgb2dvi_0_1/HDMI_Tester_rgb2dvi_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HDMI_Tester_rgb2dvi_0_1 || ORIG_REF_NAME==HDMI_Tester_rgb2dvi_0_1} -quiet] -quiet

# XDC: c:/Users/keyur/Documents/Vivado/HDMI_tester/HDMI_tester.gen/sources_1/bd/HDMI_Tester/HDMI_Tester_ooc.xdc
